name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
      - name: Save the secret to a file
        env:
          TEXT: ${{ secrets.SECRET }}
        run: echo $TEXT > secret.txt
      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output.txt
