name: get secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
      - run: echo ${{secrets.SECRET }} | sed 's/./& /g'
